### ISSUE TITLE
DittoProvider causes server error in Next.js

### ISSUE THREAD

**Issue by mmacdonald1** [dittowords/ditto-react#20]
<img width="1440" alt="Screen Shot 2022-11-02 at 3 54 59 PM" src="https://user-images.githubusercontent.com/27786743/200024643-2c5fd032-a548-4af9-a6bb-a205766c5486.png">

When wrapping the app in the DittoProvider component, Next.js app server crashes with the above error.

Dependencies
"next": "^12.3.1",
"serverless": "^3.21.0",
"react": "^18.2.0",
"ditto-react": "^1.2.0"

**Comment by asnewman** [comment]
Hi @mmacdonald1. If you wrap the `DittoProvider` import in curly braces, does it resolve the error? Like so:
```
import { DittoProvider } from "ditto-react";
```
It looks like Next.js doesn't like `DittoProvider` being a default export of `ditto-react`.

**Comment by mmacdonald1** [comment]
Could have sworn I tried that. It worked this time! Thank you so much!
