### ISSUE TITLE
`variables` prop doesn't interpolate values when using the `flat` format

### ISSUE THREAD

**Issue by int001024** [dittowords/ditto-react#23]
<Ditto textId={textId} variables={{ itemName: "apples" }} />
output = "The cart contains {{itemName}}."

Anything that I miss?

**Comment by azjgard** [comment]
Hi @int001024, thanks for opening!

I just ran the example project, and it looks like things are working there:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/19500384/212996055-07fb0b4e-b5c4-48bd-bd4c-a69354475d10.png">

It would be helpful if you could share the following:
- are you using the example project, or is this a project of your own?
- if this is a project of your own:
    - what does the contents of your `ditto` folder look like?
    - do you have the `itemName` variable configured in Ditto for this text item?

The current behavior is such that variable placeholders will not be interpolated unless corresponding variable values exist in the output generated by the CLI.

Feel free to respond with the above, and hopefully we can get this resolved for you shortly!

**Comment by int001024** [comment]
Thanks for the reply. Sorry, with `componentId` instead of `textId` it does not work. Did not notice I copied the wrong thing.

`<Ditto componentId="existing.component.id" variables={{ itemName: "apples" }} />`,

and the component id exists in the json file from the cli, like this `"existing.component.id": "Fruit {{itemName}}"`.

The output would be `"Fruit {{itemName}}"`, expected output should be `Fruit apples`

Btw, using hook approach also does not work useDittoComponent({ componentId: 'existing.component.id' })

**Comment by azjgard** [comment]
> Thanks for the reply. Sorry, with componentId instead of textId it does not work. Did not notice I copied the wrong thing.

No problem!

Running the example app again, it appears that `componentId` is working for me as well, whether using the hook or using the React component:
<img width="763" alt="image" src="https://user-images.githubusercontent.com/19500384/213181658-270c34ca-e24d-4eab-8a30-7cde6f10d24c.png">
<img width="557" alt="image" src="https://user-images.githubusercontent.com/19500384/213181741-39cbd517-12f3-42cd-85d8-78eb497396b4.png">

This is the corresponding JSON from the CLI output:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/19500384/213183665-1e37cdce-eeef-4b5e-aaf1-4e2908a93d7d.png">

This is what the corresponding component looks like configured in Ditto:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/19500384/213184717-671fbb05-8725-40ef-b823-15a2bba23cca.png">
<img width="336" alt="image" src="https://user-images.githubusercontent.com/19500384/213184780-9c532a0c-a022-452c-918f-515f22b9e097.png">

A few things to make sure of:
- your component in Ditto is configured with a variable named `itemName` (like the Ditto screenshots above)
- your CLI output contains the `variables` property like in the screenshot above, which includes a nested property named `itemName` (like JSON screenshot above)
- extending the last bullet, you're using either the default or the `structured` formats for your CLI configuration; the `flat` format doesn't include variable information (we could do a better job at explicitly documenting this!) and won't properly interpolate

Let me know if you've double checked all of the above. Sharing your broader app code, your CLI configuration, and the name of your Ditto workspace would all enable me to debug further!

**Comment by int001024** [comment]
Alright, I am using the `flat` format. I guess that is the reason. but why it cannot be supported? seems easy to support, I even made a workaround in just a few lines.

```
export function useDittoWrapper(args: Args) {
    let text = useDittoComponent(args);
    if (args.variables !== undefined) {
        Object.entries(args.variables).forEach(([k, v]) => {
            text = text?.replace(`{{${k}}}`, v.toString()) || null;
        });
    }
    return text || args.componentId;
}
```

**Comment by azjgard** [comment]
Glad we discovered the issue!

Since variable data from Ditto includes information about fallback text etc, an explicit design decision was originally made to not interpolate variable values unless there is corresponding variable data from Ditto to pull from. This guarantees to the user that when interpolation occurs, the interpolation is being done using the linked Ditto data.

We're very open to feedback! I'd love to hear more about your use case. Is there a particular reason you prefer the `flat` format over the `structured` format for integrating Ditto into your React app?

**Comment by int001024** [comment]
Thanks for the explanation! The reason is: it is shorter and easier to read.

**Comment by azjgard** [comment]
@int001024 Thanks, that makes sense! 

Are you planning on using the metadata for variables (fallback text, example text, link types) in any meaningful way (in your React app or otherwise), or do you intend to always treat them as generic placeholders for runtime values?

**Comment by int001024** [comment]
So far just a placeholder for runtime values. I think a default value is more of the job of the application side.

**Comment by azjgard** [comment]
Got it, thanks for all of the feedback!

I'm going to mark this issue as closed, but feel free to re-open it or open another issue if you run into any further problems or have additional questions :)

**Comment by azjgard** [comment]
One last update here @int001024: I just opened a PR that updates the documentation to specifically mention this. Thanks so again for surfacing!

**Comment by int001024** [comment]
Perfect! Thank you very much for the quick resolving! @azjgard

**Comment by azjgard** [comment]
Hi @int001024, after some internal discussion, we decided to implement support for using `variables` with the `flat` format -- if you upgrade to `1.3.0`, it should now be supported.

Let me know if you run into any issues!

**Comment by int001024** [comment]
Thank you for letting me know. We switched to `default` format after some internal discussions, the `plural` feature was also not working on `flat` format.
