### ISSUE TITLE
Plurals don't work with flat format

### ISSUE THREAD

**Issue by Taiwar** [dittowords/ditto-react#29]
We are experiencing this issue in an actual project with the ditto files generated by ditto-cli, but I also reproduced it in the current version of ditto-react-demo project by manually editing the files:

**Example code**

ditto-component-library__base.json
```json
{
...
  "test": "{{x}} item",
  "test_one": "{{x}} items",
  "test_two": "{{x}} items",
  "test_few": "{{x}} items",
  "test_many": "{{x}} items",
  "test_zero": "no items",
  "test_other": "{{x}} items"
}
```

index.jsx
```js
...
<Ditto componentId="test" variables={{x: 3}} count={3}/>
....
```

**Result**
"3 item"

**Expected result**
"3 items"

The same is true for any other value I set `count` to (0, 2, 20...), it always picks the value of `"test"`.

**Comment by asnewman** [comment]
Hi @Taiwar! Thanks for submitting the issue. What you experience is expected as `ditto-react`'s[ provider expects the structured format](https://github.com/dittowords/ditto-react/issues/29). Please let us know if you have any issues in regard to plurals when using the structured format. In the meantime, I will open a PR to update our README to add a disclaimer in the Plurals section to avoid confusion in the future.
