### ISSUE TITLE
How to use rich text?

### ISSUE THREAD

**Issue by int001024** [dittowords/ditto-react#34]
Hello, I see the new rich text feature, that is awesome! https://www.dittowords.com/docs/rich-text

we enabled in our project and can pull it to json files using ditto cli.

I did not find any documentation or examples how to use it in react project, could you please give some hints?

**Comment by asnewman** [comment]
Hi @int001024. Rich text isn't a support feature in ditto-react right now, but we've created tickets internally to build the feature and should be able to starting work on it soon. I will be sure to update this issue with any progress. Thank you for reporting the issue!

**Comment by asnewman** [comment]
FYI @int001024 rich text is available for Components with the merge above ^. The work for text items in a project still needs to be done though.

**Comment by s2mjredm** [comment]
I came here to ask just that question @asnewman, so thank you for the update! I thought I was missing something, but good to know it's planned. We have a single-page project where it doesn't seem to make sense to use Ditto's Components. I'll just grab the content from the JSON for now.

**Comment by asnewman** [comment]
Hi @s2mjredm! I will be sure to tag you when text items in projects are supported. Thanks for your patience!

**Comment by asnewman** [comment]
@int001024 @marc-redmond rich text is now supported for text items as of [v1.6.0](https://github.com/dittowords/ditto-react/releases/tag/v1.6.0)!
