### ISSUE TITLE
Not compatible with React 16.9.0?

### ISSUE THREAD

**Issue by BrandLibel** [dittowords/ditto-react#38]
I'm on a React 16.9 project and when I build, I get the following error:

`node_modules/ditto-react/dist/index.modern.js`
`@monument/patient: Cannot find module: 'react/jsx-runtime'. Make sure this package is installed.`

From what I understand, this error message means a React upgrade is required. Is there possibly a workaround to get ditto working otherwise?

**Comment by azjgard** [comment]
Hi @BrandLibel, thanks for opening!

Internally, we're using `ditto-react` on React version 16.12.0. I also found [a template](https://github.com/AlexLms/react-starter) online that I tweaked to spin up a React project on version 16.9, and I was able to integrate the latest version of `ditto-react` without any apparent problems.

Is it possible to make a minimum reproducible example of this for us to look at?

**Comment by BrandLibel** [comment]
@azjgard thanks for sharing that you got it working on React 16 versions. I actually tried upgrading from react 16.9 to 16.14 and this ended up fixed it for me. Not sure how you got 16.9 working but I'm guessing there was a change somewhere between React 16.9 and 16.14 that added the necessary module
