### ISSUE TITLE
How to use in React Native app?

### ISSUE THREAD

**Issue by aaquinpayan** [dittowords/ditto-react#39]
Hello! I'm setting up Ditto in a monorepo project. It's working smoothly on my web app (React) but I'm having difficulties setting it up on my mobile app (React Native Expo).

I tried this [SDK](https://github.com/dyc5828/ditto-react). This is how it appeared in my dependencies and how I used it.
<img width="477" alt="Screenshot 2024-03-11 at 10 25 59" src="https://github.com/dittowords/ditto-react/assets/16781524/0dc49b4f-ae88-4722-a2a0-c36d95f32752">

`import DittoProvider from 'ditto-react-native';`

### Error:
<img width="434" alt="Screenshot 2024-03-11 at 10 26 17" src="https://github.com/dittowords/ditto-react/assets/16781524/173a4832-e023-483d-93fa-6c7c0fe5c436">

I also noticed in `node_modules` that the package only contains these files:
<img width="217" alt="Screenshot 2024-03-11 at 10 27 11" src="https://github.com/dittowords/ditto-react/assets/16781524/80ba9f31-771d-4bf9-8a27-19be16a7cf2c">

Please help me with this as we plan on using Ditto for our project. Thank you so much!

**Comment by azjgard** [comment]
Hi @aaquinpayan, thanks for opening this issue!

It's worth calling out that the linked SDK is a forked version of the Ditto-maintained `ditto-react` library; we've never officially provided React Native support, but I'll take a look right now and see how big the lift is to get things working 😄

**Comment by aaquinpayan** [comment]
@azjgard you're right, `import { DittoProvider } from "ditto-react";` solved the issue without needing to install the forked package. Thanks so much for your assistance!
